# Generated by Django 3.2.7 on 2021-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0002_auto_20211002_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_home',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='url_monitor',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
