# Generated by Django 3.2.7 on 2021-10-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawler', '0005_url_crawler_list_url_crawler_ohter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url_crawler_ohter',
            new_name='Url_crawler_other',
        ),
    ]
